# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  GITHUB_DOCKER_REGISTRY: docker.pkg.github.com
  REPOSITORY_NAME: sidaty
  PROJECT_NAME: test-github-actions
  PACKAGE_NAME: test-github-actions

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout source code
      uses: actions/checkout@v2
    
    - name: Clean and install docker
      run: sudo mvn clean package

    # Runs a single command using the runners shell
    - name: Install Docker
      uses: docker-practice/actions-setup-docker@0.0.1
    
    
    - name: Docker build
      run: |
        docker build -t $GITHUB_DOCKER_REGISTRY/$REPOSITORY_NAME/$PROJECT_NAME/$PACKAGE_NAME .     
    - name: Docker login
      run: |
        docker login $GITHUB_DOCKER_REGISTRY -u ${{secrets.USER_NAME}} -p ${{secrets.GITHUB_TOKEN}}     
    - name: Docker push       
      run: |         
        docker push $GITHUB_DOCKER_REGISTRY/$REPOSITORY_NAME/$PROJECT_NAME/$PACKAGE_NAME
